persisted storage transfer page hashmap
Wenbin1002/matrixone pull request #2
Opened 2024-06-21 10:12 UTC by Wenbin1002

## What type of PR is this?

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #16953

## What this PR does / why we need it:

2024-06-21 10:39 UTC, Wenbin1002 commented on pkg/sql/parsers/dialect/mysql/mysql_sql.go
删掉

2024-06-21 10:39 UTC, Wenbin1002 commented on pkg/vm/engine/tae/blockio/read.go
> +func NewBlockRead() *BlockReadImpl {
改为单例模式，不要每次重新创建

2024-06-21 10:39 UTC, Wenbin1002 commented on pkg/vm/engine/tae/model/pages.go
> +
加一个任务队列，用一个goroutine来处理

2024-06-21 10:39 UTC, Wenbin1002 commented on pkg/vm/engine/tae/model/pages.go
> +}
直接强转

2024-06-21 10:39 UTC, Wenbin1002 commented on proto/api.proto
> +}
直接强转bytes

2024-06-25 09:50 UTC, aptend commented on pkg/vm/engine/tae/blockio/read.go
> +type BlockReadImpl struct{}
func (blk BlockReadImpl) LoadTableByBlock(loc, fs) { ... }

用 NewBlockRead 的地方直接用 BlockReadImpl 可不可以？

2024-06-25 09:50 UTC, aptend commented on pkg/vm/engine/tae/model/pages.go
> +	var mapping api.HashPageMap
最初的 page 为什么不构建成 api.HashPageMap?

2024-06-25 09:51 UTC, aptend commented on pkg/vm/engine/tae/model/pages.go
> +	var mapping api.HashPageMap
可以先在 50 上跑几次，看看 metric 的情况吧。跑的时候我可以再看看代码

2024-07-02 07:32 UTC, aptend commented on pkg/vm/engine/tae/tables/txnentries/mergeobjects.go
> +		_ = entry.rt.TransferTable.DeletePage(id)
这个地方只是删除了内存的page，磁盘上的没有清理？

2024-07-02 10:30 UTC, Wenbin1002 commented on pkg/vm/engine/tae/tables/txnentries/mergeobjects.go
> +		_ = entry.rt.TransferTable.DeletePage(id)
按照之前的逻辑，如果从table里delete page，那这个page磁盘就永远不会被删除了，我改了一下，你看看还有没有问题。

2024-07-10 03:59 UTC, aptend requested changes

2024-07-10 03:59 UTC, aptend commented on pkg/vm/engine/tae/tables/txnentries/flushTableTail.go
> +		model.SetFileService(entry.rt.Fs.Service)
为什么不放循环外？

2024-07-10 03:59 UTC, aptend commented on pkg/vm/engine/tae/tables/txnentries/flushTableTail.go
> +		mapping := make(map[uint32][]byte, 10)
容量为什么不用 len(m)?

2024-07-10 03:59 UTC, aptend commented on pkg/vm/engine/tae/tables/txnentries/flushTableTail.go
> +	var writer *objectio.ObjectWriter
没有直接写fs的writer?

2024-07-10 03:59 UTC, aptend commented on pkg/vm/engine/tae/tables/txnentries/flushTableTail.go
> +		err := vector.AppendBytes(v, data, false, entry.rt.VectorPool.Transient.GetMPool())
系统有限制，不能分配超过 1g 的 vector，不然会报错，所以用文件直接写更好。如果要压缩的话，可以先看 lz4 能压多少

2024-07-10 03:59 UTC, aptend commented on pkg/vm/engine/tae/model/transfer.go
> +	if len(table.pages) == 0 || table.pages[*id] == nil {
这一段啥意思？无论判不判断都return

2024-07-10 03:59 UTC, aptend commented on pkg/vm/engine/tae/model/transfer.go
> +		if st == 1 {
整型也要用变量名指明意思

2024-07-10 06:02 UTC, aptend commented on pkg/vm/engine/tae/tables/txnentries/flushTableTail.go
> +		err := vector.AppendBytes(v, data, false, entry.rt.VectorPool.Transient.GetMPool())
超过1g这个应该不用担心了，这边是一个object写一个文件，想要超过1g，这个object起码得5000w行，我们目前应该不会出现这么大的 object

2024-07-10 06:05 UTC, aptend requested changes

2024-07-10 06:05 UTC, aptend commented on pkg/vm/engine/tae/tables/txnentries/mergeobjects.go
> +				return
flushTableTail 和 merobjects 这两处写文件的逻辑，统一封装一下，避免重复

2024-07-12 02:36 UTC, aptend requested changes

2024-07-12 02:36 UTC, aptend commented on pkg/tnservice/factory.go
> +	list, _ := localFs.List(ctx, "transfer")
删除的操作放到 open 里面好些

2024-07-12 05:29 UTC, closed without merging